FROM eclipse-temurin:17.0.7_7-jdk AS cache

RUN apt-get -y update && \
    apt-get -y upgrade

ENV TZ=Asia/Seoul

RUN rm /usr/bin/curl

COPY . /app
WORKDIR /app

RUN ./gradlew assemble && \
    rm -rf /app \
