#Dockerfile
FROM jenkins/jenkins:lts

USER root

RUN apt-get update

RUN curl -fsSL https://get.docker.com/ | sh

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"

RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
